-- Disable RLS for development (re-enable when adding auth)
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE application_trackers DISABLE ROW LEVEL SECURITY;
ALTER TABLE alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE planning_decisions DISABLE ROW LEVEL SECURITY;
ALTER TABLE lpas DISABLE ROW LEVEL SECURITY;
ALTER TABLE policy_chunks DISABLE ROW LEVEL SECURITY;
ALTER TABLE decision_embeddings DISABLE ROW LEVEL SECURITY;
